/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import interfaces.InterfaceServidor;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author allan
 */
public class InicialMenu extends javax.swing.JFrame {

    /**
     * Creates new form InicialMenu
     */

    ProductList p= null;
    BidRegister bidRegister = null;
    AuctionRegister auctionRegister = null;
    public InicialMenu() {
        p = new ProductList(this);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                p.setVisible(false);
            }
        });
        bidRegister = new BidRegister(this);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                bidRegister.setVisible(false);
            }
        });
        auctionRegister = new AuctionRegister(this);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                auctionRegister.setVisible(false);
            }
        });

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casdastro = new javax.swing.JButton();
        leiloar = new javax.swing.JButton();
        darLance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        casdastro.setText("Cadastrar");
        casdastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casdastroActionPerformed(evt);
            }
        });

        leiloar.setText("Leiloar");
        leiloar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leiloarActionPerformed(evt);
            }
        });

        darLance.setText("Lances");
        darLance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darLanceActionPerformed(evt);
            }
        });

        jLabel1.setText("Bem vindo!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(casdastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(leiloar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(darLance)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casdastro)
                    .addComponent(leiloar)
                    .addComponent(darLance))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void leiloarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leiloarActionPerformed
        try {
            p.atualiza();
        } catch (RemoteException ex) {
            Logger.getLogger(InicialMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_leiloarActionPerformed

    private void darLanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darLanceActionPerformed
        bidRegister.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_darLanceActionPerformed

    private void casdastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casdastroActionPerformed
        auctionRegister.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_casdastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton casdastro;
    private javax.swing.JButton darLance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton leiloar;
    // End of variables declaration//GEN-END:variables
}
